apiVersion: skaffold/v1beta13
kind: Config
deploy:
  kubectl:
    manifests:
      - k8s-production-*
build:
  artifacts:
  - image: gcr.io/aivision-app/detectron
    context: ..
    docker:
      dockerfile: detectron/Dockerfile
      target: production
profiles:
- name: dev
  activation:
    - command: dev
  deploy:
    kubectl:
      manifests:
        - k8s-dev-*
  build:
    artifacts:
    - image: gcr.io/aivision-app/detectron
      context: ..
      sync:
        manual:
          - src: 'detectron/src/*.py'
            dest: /src
            strip: 'detectron/src/'
      docker:
        dockerfile: detectron/Dockerfile
        target: dev
